export const arrayItems = [
  {
    name: "Q&A",
    id: "q&a",
    description: "Répondre aux questions en fonction des connaissances existantes.",
    option: {
      model: "text-davinci-003",
      temperature: 0,
      max_tokens: 4000,
      top_p: 1,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
  {
    name: "Grammer Correction",
    id: "grammerCorrection",
    description: "Corriger les phrases en francais standard.",
    option: {
      model: "text-davinci-003",
      temperature: 0,
      max_tokens: 2000,
      top_p: 1,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
  {
    name: "Résumé pour un etudiant de master",
    id: "summary",
    description: "Traduit un texte difficile en concepts plus simples.",
    option: {
      model: "text-davinci-003",
      temperature: 0.7,
      max_tokens: 2000,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
  {
    name: "Traduire l' anglais pour d' autres langages",
    id: "translate",
    description: "Translates French text into English, Spanish and Japanese and more.",
    option: {
      model: "text-davinci-003",
      temperature: 0.3,
      max_tokens: 2000,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
  {
    name: "Movie to Emoji",
    id: "movieToEmoji",
    description: "Convertir des titres de films en emoji.",
    option: {
      model: "text-davinci-003",
      temperature: 0,
      max_tokens: 2000,
      top_p: 1,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
  {
    name: "Explain code",
    id: "explainCode",
    description: "Expliquer un bout de code compliqué.",
    option: {
      model: "code-davinci-002",
      temperature: 0,
      max_tokens: 2000,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
  {
    name: "JavaScript to Python",
    id: "jstopy",
    description: "Convertissez des expressions JavaScript simples en Python.",
    option: {
      model: "code-davinci-002",
      temperature: 0,
      max_tokens: 2000,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
];
